orb:
    num_keypoints: 8000
    scale_factor: 1.2
    level_pyramid: 4
    edge_threshold: 31
    first_level: 0
    WTA_K: 2
    patch_size: 31
    fast_threshold: 20
    max_num_keypoints: 1500

triangulation:
    min_angle: 1
    max_ratio_between_max_and_med_angle: 20

guided_search:
    search_window: 40
    min_distance: 20

PnP:
    reprojection_threshold: 2
    confidence: 0.999
    iterations: 1000

matches:
    min: 20

keyframe:
    distance: 1
    angle: 10

map:
    match_view_ratio: 0.1
    view_angle_threshold: 45