generic:
    debug: True

camera:
    fx: 718.86
    fy: 718.86
    cx: 607.19
    cy: 185.22
    width: 1243
    height: 376

orb:
    num_keypoints: 8000
    scale_factor: 1.2
    level_pyramid: 8
    edge_threshold: 31
    first_level: 0
    WTA_K: 2
    patch_size: 31
    fast_threshold: 20
    max_num_keypoints: 1500

initialization:
    min_num_triang_points: 100 
    reprojection_threshold: 4.0
    min_parallax: 2.0
    matches:
        min: 200
        lowe_ratio: 0.9

tracking:
    min_parallax: 2.0
    PnP:
        reprojection_threshold: 4.0
        confidence: 0.99
        iterations: 3000
        min_inliers: 4

point_association:
    num_matches: 10
    search_window: 200
    hamming_threshold: 100

keyframe:
    num_tracked_points: 5

map:
    match_view_ratio: 0.25
    min_observations: 3
    min_triang_angle: 5.0
    max_reproj_threshold: 4.0

convisibility:
    min_common_edges: 15
    essential_common_edges: 100

ba:
    num_observations: 3
    frequency: 5
    measurement_noise: 2.0

place_recognition:
    vocab_size: 1000
    similarity_threshold: 0.8
    