generic:
    debug: True
    parallel: True
    scene: "00"

camera:
    fx: 718.86
    fy: 718.86
    cx: 607.19
    cy: 185.22
    width: 1243
    height: 376

orb:
    num_keypoints: 8000
    scale_factor: 1.2
    level_pyramid: 8
    edge_threshold: 31
    first_level: 0
    WTA_K: 2
    patch_size: 31
    fast_threshold: 20
    max_num_keypoints: 1500

place_recognition:
    vocab_size: 1000
    similarity_threshold: 0.8


initialization:
    min_matches: 200
    lowe_ratio: 0.75
    min_triang_points: 100 
    min_parallax: 2.0
    max_reprojection: 4.0

tracking:
    min_matches: 20
    lowe_ratio: 0.75
    PnP:
        max_reprojection: 4.0
        confidence: 0.99
        iterations: 3000
        min_inliers: 4

map:
    lowe_ratio: 0.75
    min_parallax: 2.0
    max_reprojection: 4.0
    point_culling_ratio: 0.25
    kf_culling_ratio: 0.9

loop:
    lowe_ratio: 0.9
    min_matches: 20
    PnP:
        max_reprojection: 4.0
        confidence: 0.99
        iterations: 3000
        min_inliers: 4

keyframe:
    t: 2
    r: 5
    num_tracked_points: 20
    common_feat_ratio: 0.9

convisibility:
    min_common_edges: 15
    essential_common_edges: 100

