generic:
    debug: True

camera:
    fx: 718.86
    fy: 718.86
    cx: 607.19
    cy: 185.22
    width: 1243
    height: 376

orb:
    num_keypoints: 8000
    scale_factor: 1.2
    level_pyramid: 8
    edge_threshold: 31
    first_level: 0
    WTA_K: 2
    patch_size: 31
    fast_threshold: 20
    max_num_keypoints: 1500

triangulation:
    min_angle: 0.5
    max_ratio_between_max_and_med_angle: 20

point_association:
    num_matches: 40

PnP:
    reprojection_threshold: 2.0
    confidence: 0.999
    iterations: 300
    min_inliers: 4

matches:
    min: 20
    lowe_ratio: 0.8
    xiang_gao_match_ratio: 2

keyframe:
    distance: 0.5
    angle: 10
    num_tracked_points: 20

map:
    match_view_ratio: 0.25
    min_observations: 3
    max_keyframes_since_last_observation: 10

ba:
    min_pose_connections: 5
    min_landmark_observations: 5
    frequency: 10
    first_pose_noise: 1e-9 # Std. deviation for the first robot pose (meters)
    odometry_trans_noise: 1.0  # Std. deviation for the calculated odometry (meters)
    odometry_rot_noise: 2.0    # Std. deviation for the calculated odometry (degrees)
    first_measurement_noise: 0.1  # Std. deviation for the first landmark observation (meters)
    measurement_noise: 2.0  # Std. deviation for camera measurements (pixels)
